#!/bin/bash
set -euo pipefail

DOTFILES_DIR="$(cd "$(dirname "$0")" && pwd)"
# バックアップはリポ外に置く（.npmrc 等の認証情報が Git 追跡下に紛れ込むのと、
# basename 衝突で settings.json 同士が上書きし合うのを避けるため。元のパス構造を保持する）
BACKUP_DIR="${XDG_STATE_HOME:-$HOME/.local/state}/dotfiles/backups/$(date +%Y%m%d_%H%M%S)"

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

info()  { echo -e "${GREEN}[OK]${NC} $1"; }
warn()  { echo -e "${YELLOW}[SKIP]${NC} $1"; }
error() { echo -e "${RED}[ERROR]${NC} $1"; }

backup_and_link() {
    local src="$1"
    local dest="$2"

    if [ ! -e "$src" ]; then
        error "Source not found: $src"
        return
    fi

    # If destination is already a symlink to the right place, skip
    if [ -L "$dest" ] && [ "$(readlink "$dest")" = "$src" ]; then
        warn "Already linked: $dest"
        return
    fi

    # Backup existing file/dir（$HOME からの相対パス構造を保持し、同名 basename の衝突を防ぐ）
    if [ -e "$dest" ] || [ -L "$dest" ]; then
        local rel="${dest#"$HOME"/}"
        local backup_target="$BACKUP_DIR/$rel"
        mkdir -p "$(dirname "$backup_target")"
        mv "$dest" "$backup_target"
        warn "Backed up: $dest -> $backup_target"
    fi

    # Create parent directory if needed
    mkdir -p "$(dirname "$dest")"

    ln -s "$src" "$dest"
    info "Linked: $dest -> $src"
}

echo "=== dotfiles setup ==="
echo "Dotfiles dir: $DOTFILES_DIR"
echo ""

# --- Shell ---
echo "--- Shell ---"
backup_and_link "$DOTFILES_DIR/shell/.zshrc"      "$HOME/.zshrc"
backup_and_link "$DOTFILES_DIR/shell/.zprofile"   "$HOME/.zprofile"
backup_and_link "$DOTFILES_DIR/shell/.zshenv"     "$HOME/.zshenv"
backup_and_link "$DOTFILES_DIR/shell/.zpreztorc"  "$HOME/.zpreztorc"
backup_and_link "$DOTFILES_DIR/shell/.npmrc"      "$HOME/.npmrc"

# --- Git ---
echo "--- Git ---"
backup_and_link "$DOTFILES_DIR/git/.gitconfig"        "$HOME/.gitconfig"
backup_and_link "$DOTFILES_DIR/git/.gitignore_global"  "$HOME/.gitignore_global"

# Set git user.email if not already configured (per-machine: ~/.gitconfig.local)
# NOTE: --global で書くと symlink 先の repo ファイルを汚すので必ず --file で書く
if [ -z "$(git config --includes --global user.email)" ]; then
    printf "Git user.email is not set. Enter your email: "
    read -r GIT_EMAIL
    git config --file "$HOME/.gitconfig.local" user.email "$GIT_EMAIL"
    info "Set git user.email to $GIT_EMAIL (in ~/.gitconfig.local)"
fi

# --- WezTerm ---
echo "--- WezTerm ---"
backup_and_link "$DOTFILES_DIR/terminal/wezterm/wezterm.lua"  "$HOME/.config/wezterm/wezterm.lua"
backup_and_link "$DOTFILES_DIR/terminal/wezterm/keybinds.lua" "$HOME/.config/wezterm/keybinds.lua"

# --- Neovim ---
echo "--- Neovim ---"
backup_and_link "$DOTFILES_DIR/nvim" "$HOME/.config/nvim"

# --- Karabiner-Elements ---
# 設定保存時に rename されるためファイル単体ではなくディレクトリごと symlink する
echo "--- Karabiner-Elements ---"
backup_and_link "$DOTFILES_DIR/karabiner" "$HOME/.config/karabiner"

# --- VS Code ---
echo "--- VS Code ---"
VSCODE_USER="$HOME/Library/Application Support/Code/User"
if [ -d "$VSCODE_USER" ]; then
    backup_and_link "$DOTFILES_DIR/editor/vscode/settings.json" "$VSCODE_USER/settings.json"
    [ -f "$DOTFILES_DIR/editor/vscode/keybindings.json" ] && \
        backup_and_link "$DOTFILES_DIR/editor/vscode/keybindings.json" "$VSCODE_USER/keybindings.json"
else
    warn "VS Code not installed, skipping"
fi

# --- Cursor ---
echo "--- Cursor ---"
CURSOR_USER="$HOME/Library/Application Support/Cursor/User"
if [ -d "$CURSOR_USER" ]; then
    backup_and_link "$DOTFILES_DIR/editor/cursor/settings.json" "$CURSOR_USER/settings.json"
else
    warn "Cursor not installed, skipping"
fi

# --- Claude Code ---
echo "--- Claude Code ---"
backup_and_link "$DOTFILES_DIR/claude/settings.json"    "$HOME/.claude/settings.json"
backup_and_link "$DOTFILES_DIR/claude/CLAUDE.md"         "$HOME/.claude/CLAUDE.md"
backup_and_link "$DOTFILES_DIR/claude/keybindings.json"  "$HOME/.claude/keybindings.json"
backup_and_link "$DOTFILES_DIR/claude/statusline.sh"     "$HOME/.claude/statusline.sh"
# claude.json is auto-generated by Claude Code; not managed in dotfiles

# Claude Code hooks (スクリプトと、ガードが参照する許可リスト等の .txt 設定も1本ずつ link)
echo "--- Claude Code Hooks ---"
mkdir -p "$HOME/.claude/hooks"
for hook in "$DOTFILES_DIR/claude/hooks/"*.sh "$DOTFILES_DIR/claude/hooks/"*.txt; do
    [ -f "$hook" ] && backup_and_link "$hook" "$HOME/.claude/hooks/$(basename "$hook")"
done

# Claude Code skills (link each skill dir; plugin-provided skills are managed by the marketplace, not here)
echo "--- Claude Code Skills ---"
mkdir -p "$HOME/.claude/skills"
for skill in "$DOTFILES_DIR/claude/skills/"*/; do
    [ -d "$skill" ] && backup_and_link "${skill%/}" "$HOME/.claude/skills/$(basename "${skill%/}")"
done

# Claude Code agents (link each agent md; plugin-provided agents are managed by the marketplace, not here)
echo "--- Claude Code Agents ---"
mkdir -p "$HOME/.claude/agents"
for agent in "$DOTFILES_DIR/claude/agents/"*.md; do
    [ -f "$agent" ] && backup_and_link "$agent" "$HOME/.claude/agents/$(basename "$agent")"
done

# Claude Code failure catalogs (スタック別の失敗パターンカタログ。agents/CLAUDE.md から参照される)
echo "--- Claude Code Failure Catalogs ---"
mkdir -p "$HOME/.claude/failure-catalog"
for catalog in "$DOTFILES_DIR/claude/failure-catalog/"*.md; do
    [ -f "$catalog" ] && backup_and_link "$catalog" "$HOME/.claude/failure-catalog/$(basename "$catalog")"
done

# --- Codex CLI (hooks: WezTerm タブに Codex の稼働状態を出す) ---
# Codex は Claude と同じ wezterm-status.sh を WEZTERM_STATUS_AGENT=codex で呼ぶ。
# 反映には Codex 側で `/hooks` から trust し直す必要がある（Codex はハッシュ trust）。
echo "--- Codex ---"
backup_and_link "$DOTFILES_DIR/codex/hooks.json" "$HOME/.codex/hooks.json"
# Codex は CLAUDE.md を読まないため、両エージェント共通の運用ルールは AGENTS.md で渡す
backup_and_link "$DOTFILES_DIR/codex/AGENTS.md" "$HOME/.codex/AGENTS.md"

# --- mise ---
echo "--- mise ---"
backup_and_link "$DOTFILES_DIR/mise/config.toml" "$HOME/.config/mise/config.toml"

# --- launchd (morning-prep / collect-feed-prep) ---
echo "--- launchd ---"
for LAUNCHD_LABEL in com.masahrosanya.morning-prep com.masahrosanya.collect-feed-prep; do
    LAUNCHD_PLIST="$HOME/Library/LaunchAgents/${LAUNCHD_LABEL}.plist"
    backup_and_link "$DOTFILES_DIR/launchd/${LAUNCHD_LABEL}.plist" "$LAUNCHD_PLIST"
    if launchctl print "gui/$(id -u)/${LAUNCHD_LABEL}" >/dev/null 2>&1; then
        warn "launchd already loaded: ${LAUNCHD_LABEL}"
    elif launchctl bootstrap "gui/$(id -u)" "$LAUNCHD_PLIST" 2>/dev/null; then
        info "launchd loaded: ${LAUNCHD_LABEL}"
    else
        error "launchctl bootstrap failed: ${LAUNCHD_PLIST}"
    fi
done

# --- Git hooks (dotfiles リポ自身の pre-commit) ---
echo "--- Git hooks ---"
if git -C "$DOTFILES_DIR" rev-parse --git-dir >/dev/null 2>&1; then
    git -C "$DOTFILES_DIR" config core.hooksPath .githooks
    info "git core.hooksPath -> .githooks"
else
    warn "dotfiles is not a git repo, skipping hooksPath"
fi

echo ""
echo "=== Setup complete ==="
echo ""
echo "Next steps:"
echo "  1. Install Homebrew:  /bin/bash -c \"\$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)\""
echo "  2. Install packages:  brew bundle --file=$DOTFILES_DIR/Brewfile"
echo "  3. Install anyenv:    anyenv install --init && anyenv install nodenv && anyenv install pyenv && anyenv install rbenv"
echo "  4. Install Node:      nodenv install 20.19.5 && nodenv global 20.19.5"
echo "  5. Install Python:    pyenv install 3.11.0 && pyenv global 3.11.0"
echo "  6. Install Ruby:      rbenv install 3.4.6 && rbenv global 3.4.6"
echo "  7. Install mise tools: mise install"
echo "  8. Auth GitHub:       gh auth login"
echo "  9. Auth GCP:          gcloud auth login && gcloud auth application-default login"
echo " 10. Claude Code settings.local.json は手動で設定（許可ルール・プラグイン等）"
